apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld-one-clusterip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld-one-clusterip
  template:
    metadata:
      labels:
        app: aks-helloworld-one-clusterip
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: aks-helloworld-one-clusterip
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-one-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld-one-clusterip
